platform :ios, '6.0'

pod 'AFNetworking'
pod 'GoogleAnalytics-iOS-SDK'
pod 'JLRoutes', '~> 1.2'
pod 'Mantle', '~> 1.0'
pod 'MapBox'
pod 'SSToolkit'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'TestFlightSDK'
pod 'TSMessages'
pod 'TTTAttributedLabel'
pod 'ViewDeck', '~> 2.2.8'
